language: python
python:
  - "3.6"
# command to install dependencies
services:
    - postgresql
install:
    - pip install .
    - pip install codecov
    - pip install pylint
# command to run tests
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
script:
    - python setup.py test
after_script:
    - codecov
addons:
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10

    postgresql: 10
env:
    global:
        - PGPORT=5433

