language: python
python:
  - "3.6"
# command to install dependencies
services:
    - postgresql
install:
    - pip install .
# command to run tests
before_script:
    - bash tests/create_usrconf.sh
script:
    - python setup.py test
