language: python
python:
  - "3.6"
# command to install dependencies
services:
    - postgresql
install:
    - pip install .
    - pip install codecov
    - pip install pylint
# command to run tests
script:
    - python setup.py test
after_script:
    - codecov
addons:
    postgresql: "10"
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10
env:
    global:
        - PGPORT=5432

