\i nordic_event_root.sql
\i nordic_file.sql
\i nordic_event.sql
\i scandia_header.sql
\i nordic_modified.sql
\i nordic_header_main.sql
\i nordic_header_error.sql
\i nordic_header_comment.sql
\i nordic_header_macroseismic.sql
\i nordic_header_waveform.sql
\i nordic_phase_data.sql
