CREATE TABLE scandia_header(
	id SERIAL PRIMARY KEY,
	event_id INTEGER REFERENCES nordic_event(id),
	source_ref VARCHAR(3),
	origin_questionability VARCHAR(1),
	year INTEGER,
	month INTEGER,
	day INTEGER,
	hour INTEGER,
	minute INTEGER,
	second FLOAT,
	epicenter_latitude FLOAT,
	epicenter_longitude FLOAT,
	origin_time_uncertainty VARCHAR(1),
	location_uncertainty VARCHAR(1),
	focal_depth INTEGER,
	depth_identification_code varchar(1),
	magnitude_1 FLOAT,
	magnitude_scale_1 VARCHAR(2),
	magnitude_2 FLOAT,
	magnitude_scale_2 VARCHAR(2),
	magnitude_3 FLOAT,
	magnitude_scale_3 VARCHAR(2),
	maximum_intensity VARCHAR(4),
	macroseismic_observation_flag VARCHAR(1),
	macroseismic_reference VARCHAR(3),
	mean_radius_of_area_percetibility INTEGER,
	region_code VARCHAR(1),
	number_of_stations_used INTEGER,
	max_azimuth_gap VARCHAR(3),
	min_epicenter_to_station_distance VARCHAR(5)
);
